# Generated by Django 3.2.14 on 2023-02-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='numberofdays',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
