# Generated by Django 3.2.14 on 2023-02-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_booking_numberofdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paymentstatus',
            field=models.BooleanField(default=False),
        ),
    ]
