# Generated by Django 3.2.14 on 2023-02-03 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Name', models.CharField(max_length=255)),
                ('Car_Brand', models.CharField(max_length=255)),
                ('Car_Category', models.CharField(max_length=255)),
                ('Plate_Number', models.CharField(max_length=255)),
                ('Model_Year', models.DateField()),
                ('Car_Image', models.ImageField(upload_to='car_image')),
                ('Manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
