# Generated by Django 3.2.14 on 2023-02-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='Car_Status',
            field=models.CharField(choices=[('Listed For Rentel', 'Listed For Rentel'), ('Not Listed For Rentel', 'Not Listed For Rentel'), ('In Garrage', 'In Garrage'), ('On Rentel', 'On Rentel')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Car_Category',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('MUV', 'MUV'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Pickup Truck', 'Convertible')], max_length=255),
        ),
    ]
