# Generated by Django 3.2.14 on 2023-02-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_cars_kilomeaters'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='Rent',
            field=models.CharField(default=1000, max_length=12),
            preserve_default=False,
        ),
    ]
